convoy-gluster:
    labels:
        io.rancher.container.create_agent: 'true'
        io.rancher.scheduler.global: 'true'
        io.rancher.scheduler.affinity:host_label_soft: ${HOST_LABEL}
    privileged: true
    working_dir: /storage
    volumes:
        - /proc:/host/proc
        - /var/run/convoy:/var/run/convoy
        - /var/lib/convoy:/var/lib/convoy
        - /etc/docker/plugins:/etc/docker/plugins
        - /storage
    image: rancher/convoy-gluster-volume-agent:v0.1.0-rc1
convoy-gluster-storagepool:
    labels:
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.affinity:host_label_soft: ${HOST_LABEL}
    image: rancher/convoy-gluster-storagepool-agent:v0.1.0-rc1
